/*
 * SPDX-FileCopyrightText: 2025 robot-visual-perception
 *
 * SPDX-License-Identifier: MIT
 */

/**
 * COCO Dataset Class Labels
 *
 * YOLOv8 is trained on the COCO (Common Objects in Context) dataset,
 * which contains 80 object classes. This array maps class IDs (0-79)
 * to human-readable labels.
 *
 * Source: https://github.com/ultralytics/ultralytics
 */
export const COCO_LABELS: string[] = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];

export const COCO_LABELS_DE: string[] = [
  'person',
  'fahrrad',
  'auto',
  'motorrad',
  'flugzeug',
  'bus',
  'zug',
  'lastwagen',
  'boot',
  'ampel',
  'hydrant',
  'stoppschild',
  'parkautomat',
  'bank',
  'vogel',
  'katze',
  'hund',
  'pferd',
  'schaf',
  'kuh',
  'elefant',
  'baer',
  'zebra',
  'giraffe',
  'rucksack',
  'regenschirm',
  'handtasche',
  'krawatte',
  'koffer',
  'frisbee',
  'ski',
  'snowboard',
  'sportball',
  'drachen',
  'baseballschlaeger',
  'baseballhandschuh',
  'skateboard',
  'surfboard',
  'tennisschlaeger',
  'flasche',
  'weinglas',
  'tasse',
  'gabel',
  'messer',
  'loeffel',
  'schuessel',
  'banane',
  'apfel',
  'sandwich',
  'orange',
  'brokkoli',
  'karotte',
  'hotdog',
  'pizza',
  'donut',
  'kuchen',
  'stuhl',
  'sofa',
  'topfpflanze',
  'bett',
  'esstisch',
  'toilette',
  'tv',
  'laptop',
  'maus',
  'fernbedienung',
  'tastatur',
  'mobiltelefon',
  'mikrowelle',
  'backofen',
  'toaster',
  'spuele',
  'kuehlschrank',
  'buch',
  'uhr',
  'vase',
  'schere',
  'teddybaer',
  'haartrockner',
  'zahnbuerste',
];

export const COCO_LABELS_FR: string[] = [
  'personne',
  'velo',
  'voiture',
  'moto',
  'avion',
  'bus',
  'train',
  'camion',
  'bateau',
  'feu de circulation',
  'borne incendie',
  'panneau stop',
  'parcmetre',
  'banc',
  'oiseau',
  'chat',
  'chien',
  'cheval',
  'mouton',
  'vache',
  'elephant',
  'ours',
  'zebre',
  'girafe',
  'sac a dos',
  'parapluie',
  'sac a main',
  'cravate',
  'valise',
  'frisbee',
  'skis',
  'snowboard',
  'ballon de sport',
  'cerf volant',
  'batte de baseball',
  'gant de baseball',
  'skateboard',
  'planche de surf',
  'raquette de tennis',
  'bouteille',
  'verre a vin',
  'tasse',
  'fourchette',
  'couteau',
  'cuillere',
  'bol',
  'banane',
  'pomme',
  'sandwich',
  'orange',
  'brocoli',
  'carotte',
  'hot dog',
  'pizza',
  'donut',
  'gateau',
  'chaise',
  'canape',
  'plante en pot',
  'lit',
  'table a manger',
  'toilettes',
  'tv',
  'ordinateur portable',
  'souris',
  'telecommande',
  'clavier',
  'telephone portable',
  'micro ondes',
  'four',
  'grille pain',
  'evier',
  'refrigerateur',
  'livre',
  'horloge',
  'vase',
  'ciseaux',
  'ours en peluche',
  'seche cheveux',
  'brosse a dents',
];

export const COCO_LABELS_ES: string[] = [
  'persona',
  'bicicleta',
  'coche',
  'motocicleta',
  'avion',
  'autobus',
  'tren',
  'camion',
  'barco',
  'semaforo',
  'hidrante',
  'senal de stop',
  'parquimetro',
  'banco',
  'pajaro',
  'gato',
  'perro',
  'caballo',
  'oveja',
  'vaca',
  'elefante',
  'oso',
  'cebra',
  'jirafa',
  'mochila',
  'paraguas',
  'bolso',
  'corbata',
  'maleta',
  'frisbee',
  'esquis',
  'snowboard',
  'pelota deportiva',
  'cometa',
  'bate de beisbol',
  'guante de beisbol',
  'skateboard',
  'tabla de surf',
  'raqueta de tenis',
  'botella',
  'copa de vino',
  'taza',
  'tenedor',
  'cuchillo',
  'cuchara',
  'tazon',
  'banana',
  'manzana',
  'sandwich',
  'naranja',
  'brocoli',
  'zanahoria',
  'hot dog',
  'pizza',
  'donut',
  'pastel',
  'silla',
  'sofa',
  'planta en maceta',
  'cama',
  'mesa de comedor',
  'inodoro',
  'tv',
  'portatil',
  'raton',
  'control remoto',
  'teclado',
  'telefono movil',
  'microondas',
  'horno',
  'tostadora',
  'fregadero',
  'refrigerador',
  'libro',
  'reloj',
  'jarron',
  'tijeras',
  'oso de peluche',
  'secador de pelo',
  'cepillo de dientes',
];

export const COCO_LABELS_IT: string[] = [
  'persona',
  'bicicletta',
  'auto',
  'motocicletta',
  'aereo',
  'bus',
  'treno',
  'camion',
  'barca',
  'semaforo',
  'idrante',
  'segnale stop',
  'parchimetro',
  'panchina',
  'uccello',
  'gatto',
  'cane',
  'cavallo',
  'pecora',
  'mucca',
  'elefante',
  'orso',
  'zebra',
  'giraffa',
  'zaino',
  'ombrello',
  'borsa',
  'cravatta',
  'valigia',
  'frisbee',
  'sci',
  'snowboard',
  'palla sportiva',
  'aquilone',
  'mazza da baseball',
  'guanto da baseball',
  'skateboard',
  'tavola da surf',
  'racchetta da tennis',
  'bottiglia',
  'bicchiere da vino',
  'tazza',
  'forchetta',
  'coltello',
  'cucchiaio',
  'ciotola',
  'banana',
  'mela',
  'panino',
  'arancia',
  'broccoli',
  'carota',
  'hot dog',
  'pizza',
  'donut',
  'torta',
  'sedia',
  'divano',
  'pianta in vaso',
  'letto',
  'tavolo da pranzo',
  'toilette',
  'tv',
  'portatile',
  'mouse',
  'telecomando',
  'tastiera',
  'telefono cellulare',
  'microonde',
  'forno',
  'tostapane',
  'lavandino',
  'frigorifero',
  'libro',
  'orologio',
  'vaso',
  'forbici',
  'orsetto',
  'asciugacapelli',
  'spazzolino',
];

export type CocoLabelLanguage = 'en' | 'de' | 'fr' | 'es' | 'it';

const LABELS_BY_LANGUAGE: Record<CocoLabelLanguage, string[]> = {
  en: COCO_LABELS,
  de: COCO_LABELS_DE,
  fr: COCO_LABELS_FR,
  es: COCO_LABELS_ES,
  it: COCO_LABELS_IT,
};

/**
 * Get human-readable label for a COCO class ID (capitalized)
 */
export function getCocoLabel(
  classId: number | string,
  language: CocoLabelLanguage = 'en',
  options?: { unknownLabel?: (value: number | string) => string }
): string {
  const id = typeof classId === 'string' ? parseInt(classId, 10) : classId;
  const labels = LABELS_BY_LANGUAGE[language] ?? COCO_LABELS;
  if (isNaN(id)) {
    if (typeof classId === 'string' && classId.trim().length > 0) {
      return classId.charAt(0).toUpperCase() + classId.slice(1);
    }
    return options?.unknownLabel?.(classId) ?? `Unknown (${classId})`;
  }
  if (id < 0 || id >= labels.length) {
    return options?.unknownLabel?.(classId) ?? `Unknown (${classId})`;
  }
  const label = labels[id];
  return label ? label.charAt(0).toUpperCase() + label.slice(1) : '';
}
